# Generated by Django 4.0.2 on 2022-02-02 23:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('path', models.CharField(max_length=255, unique=True)),
                ('depth', models.PositiveIntegerField()),
                ('numchild', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=250, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('scope', models.TextField(verbose_name='Сфера применения')),
                ('diameter', models.FloatField(validators=[django.core.validators.MinValueValidator(0.1)], verbose_name='Диаметр, мм')),
                ('length', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='Длина, мм')),
                ('color', models.CharField(max_length=250, verbose_name='Цвет')),
                ('image', models.ImageField(upload_to='media/', verbose_name='Фото товара')),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='api.category', verbose_name='Карточка товара')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
                'ordering': ('name', 'id'),
            },
        ),
    ]
